name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist

  build-desktop:
    needs: build-frontend
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: web-serial-windows
            asset_name: web-serial-windows.zip
          - os: macos-latest
            artifact_name: web-serial-macos
            asset_name: web-serial-macos.zip
          - os: ubuntu-22.04
            artifact_name: web-serial-linux
            asset_name: web-serial-linux.zip

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: window/dist

      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build desktop app
        run: |
          cd window
          go build -v -ldflags "-X main.version=${{ steps.version.outputs.VERSION }}" -o ${{ matrix.artifact_name }}

      - name: Create release asset
        run: |
          cd window
          zip -r ${{ matrix.asset_name }} ${{ matrix.artifact_name }} ./dist

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: window/${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}